package Replica2.ServerObjectInterfaceApp2;


/**
* ServerObjectInterfaceApp2/ServerObjectInterface2Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerObjectInterface.idl
* Saturday, April 8, 2023 11:14:24 o'clock PM EDT
*/

abstract public class ServerObjectInterface2Helper
{
  private static String  _id = "IDL:ServerObjectInterfaceApp2/ServerObjectInterface2:1.0";

  public static void insert (org.omg.CORBA.Any a, Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2Helper.id (), "ServerObjectInterface2");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2 read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (Replica2.ServerObjectInterfaceApp2._ServerObjectInterface2Stub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2 value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2 narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2)
      return (Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Replica2.ServerObjectInterfaceApp2._ServerObjectInterface2Stub stub = new Replica2.ServerObjectInterfaceApp2._ServerObjectInterface2Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2 unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2)
      return (Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Replica2.ServerObjectInterfaceApp2._ServerObjectInterface2Stub stub = new Replica2.ServerObjectInterfaceApp2._ServerObjectInterface2Stub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
