package Replica2.ServerObjectInterfaceApp2;


/**
* ServerObjectInterfaceApp2/ServerObjectInterface2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerObjectInterface.idl
* Saturday, April 8, 2023 11:14:24 o'clock PM EDT
*/

public interface ServerObjectInterface2 extends Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface ServerObjectInterface2
