package Replica2.ServerObjectInterfaceApp2;


/**
* ServerObjectInterfaceApp2/ServerObjectInterface2POA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ServerObjectInterface.idl
* Saturday, April 8, 2023 11:14:24 o'clock PM EDT
*/

public abstract class ServerObjectInterface2POA extends org.omg.PortableServer.Servant
 implements Replica2.ServerObjectInterfaceApp2.ServerObjectInterface2Operations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlot", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
          * Only for admin
          */
       case 0:  // ServerObjectInterfaceApp2/ServerObjectInterface2/addMovieSlot
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlot (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ServerObjectInterfaceApp2/ServerObjectInterface2/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerObjectInterfaceApp2/ServerObjectInterface2/listMovieShowAvailability
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowAvailability (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
               * Both admin and Customer
               */
       case 3:  // ServerObjectInterfaceApp2/ServerObjectInterface2/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerObjectInterfaceApp2/ServerObjectInterface2/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ServerObjectInterfaceApp2/ServerObjectInterface2/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ServerObjectInterfaceApp2/ServerObjectInterface2/exchangeTickets
       {
         String customerID = in.read_string ();
         String newMovieID = in.read_string ();
         String newMovieName = in.read_string ();
         String oldMovieID = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, newMovieID, newMovieName, oldMovieID, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // ServerObjectInterfaceApp2/ServerObjectInterface2/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerObjectInterfaceApp2/ServerObjectInterface2:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerObjectInterface2 _this() 
  {
    return ServerObjectInterface2Helper.narrow(
    super._this_object());
  }

  public ServerObjectInterface2 _this(org.omg.CORBA.ORB orb) 
  {
    return ServerObjectInterface2Helper.narrow(
    super._this_object(orb));
  }


} // class ServerObjectInterface2POA
