package Frontend.FEInterfaceApp;


/**
* FEInterfaceApp/FEObjectInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./FEInterface.idl
* Sunday, April 9, 2023 7:31:49 o'clock PM EDT
*/

public abstract class FEObjectInterfacePOA extends org.omg.PortableServer.Servant
 implements Frontend.FEInterfaceApp.FEObjectInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlot", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
          * Only for admin
          */
       case 0:  // FEInterfaceApp/FEObjectInterface/addMovieSlot
       {
         String adminID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlot (adminID, movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FEInterfaceApp/FEObjectInterface/removeMovieSlots
       {
         String adminID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (adminID, movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FEInterfaceApp/FEObjectInterface/listMovieShowAvailability
       {
         String adminID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowAvailability (adminID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
               * Both admin and Customer
               */
       case 3:  // FEInterfaceApp/FEObjectInterface/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FEInterfaceApp/FEObjectInterface/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // FEInterfaceApp/FEObjectInterface/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FEInterfaceApp/FEObjectInterface/exchangeTickets
       {
         String customerID = in.read_string ();
         String newMovieID = in.read_string ();
         String newMovieName = in.read_string ();
         String oldMovieID = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, newMovieID, newMovieName, oldMovieID, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // FEInterfaceApp/FEObjectInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FEInterfaceApp/FEObjectInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FEObjectInterface _this() 
  {
    return FEObjectInterfaceHelper.narrow(
    super._this_object());
  }

  public FEObjectInterface _this(org.omg.CORBA.ORB orb) 
  {
    return FEObjectInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class FEObjectInterfacePOA
