package Frontend.FEInterfaceApp;

/**
* FEInterfaceApp/FEObjectInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./FEInterface.idl
* Sunday, April 9, 2023 7:31:49 o'clock PM EDT
*/

public final class FEObjectInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public Frontend.FEInterfaceApp.FEObjectInterface value = null;

  public FEObjectInterfaceHolder ()
  {
  }

  public FEObjectInterfaceHolder (Frontend.FEInterfaceApp.FEObjectInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Frontend.FEInterfaceApp.FEObjectInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Frontend.FEInterfaceApp.FEObjectInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Frontend.FEInterfaceApp.FEObjectInterfaceHelper.type ();
  }

}
