package Frontend.FEInterfaceApp;


/**
* FEInterfaceApp/FEObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./FEInterface.idl
* Sunday, April 9, 2023 7:31:49 o'clock PM EDT
*/

public interface FEObjectInterface extends FEObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FEObjectInterface
