package Replica1.DMTBSapp;


/**
* DMTBSapp/DMTBSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Monday, 10 April, 2023 9:18:49 PM EDT
*/

public interface DMTBSOperations 
{

  //First Start orbd follow Command :-  orbd -ORBInitialPort 1050
  String addMovieSlots (String movieID, String movieName, int bookingCapacity);
  String removeMovieSlots (String movieID, String movieName);
  String listMovieShowsAvailability (String movieName);
  String bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String getBookingSchedule (String customerID);
  String cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String exchangeTickets (String customerID, String movieID, String new_movieID, String new_movieName, int numberOfTickets);
  void shutdown ();
} // interface DMTBSOperations
