package Replica1.DMTBSapp;


/**
* Replica1.DMTBSapp/DMTBSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Monday, 10 April, 2023 9:18:49 PM EDT
*/

abstract public class DMTBSHelper
{
  private static String  _id = "IDL:Replica1.DMTBSapp/DMTBS:1.0";

  public static void insert (org.omg.CORBA.Any a, Replica1.DMTBSapp.DMTBS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Replica1.DMTBSapp.DMTBS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Replica1.DMTBSapp.DMTBSHelper.id (), "DMTBS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Replica1.DMTBSapp.DMTBS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DMTBSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Replica1.DMTBSapp.DMTBS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Replica1.DMTBSapp.DMTBS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Replica1.DMTBSapp.DMTBS)
      return (Replica1.DMTBSapp.DMTBS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Replica1.DMTBSapp._DMTBSStub stub = new Replica1.DMTBSapp._DMTBSStub ();
      stub._set_delegate(delegate);
      return (DMTBS) stub;
    }
  }

  public static Replica1.DMTBSapp.DMTBS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Replica1.DMTBSapp.DMTBS)
      return (Replica1.DMTBSapp.DMTBS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Replica1.DMTBSapp._DMTBSStub stub = new Replica1.DMTBSapp._DMTBSStub ();
      stub._set_delegate(delegate);
      return (DMTBS) stub;
    }
  }

}
