package Replica3.DMTBSApp;


/**
* DMTBSApp/DMTBSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBSApp.idl
* Monday, April 10, 2023 9:29:09 o'clock PM EDT
*/

public interface DMTBSOperations 
{
  String addMovieSlots (String movieID, String movieName, String[] bookingCapacity);
  String removeMovieSlots (String movieID, String movieName);
  String[] listMovieShowsAvailability (String movieName);
  String bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String[] getBookingSchedule (String customerID);
  String cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String exchangeTickets (String customerID, String oldMovieID, String newMovieID, String newMovieName, int numberOfTickets);
  void shutdown ();
} // interface DMTBSOperations
