package Replica3.DMTBSApp;

/**
* DMTBSApp/DMTBSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBSApp.idl
* Monday, April 10, 2023 9:29:09 o'clock PM EDT
*/

public final class DMTBSHolder implements org.omg.CORBA.portable.Streamable
{
  public Replica3.DMTBSApp.DMTBS value = null;

  public DMTBSHolder ()
  {
  }

  public DMTBSHolder (Replica3.DMTBSApp.DMTBS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Replica3.DMTBSApp.DMTBSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Replica3.DMTBSApp.DMTBSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Replica3.DMTBSApp.DMTBSHelper.type ();
  }

}
