package Replica3.DMTBSApp;


/**
* DMTBSApp/DMTBSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBSApp.idl
* Monday, April 10, 2023 9:29:09 o'clock PM EDT
*/

public abstract class DMTBSPOA extends org.omg.PortableServer.Servant
 implements Replica3.DMTBSApp.DMTBSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DMTBSApp/DMTBS/addMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String bookingCapacity[] = DMTBSApp.DMTBSPackage.listHelper.read (in);
         String $result = null;
         $result = this.addMovieSlots (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DMTBSApp/DMTBS/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DMTBSApp/DMTBS/listMovieShowsAvailability
       {
         String movieName = in.read_string ();
         String $result[] = null;
         $result = this.listMovieShowsAvailability (movieName);
         out = $rh.createReply();
         DMTBSApp.DMTBSPackage.listHelper.write (out, $result);
         break;
       }

       case 3:  // DMTBSApp/DMTBS/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DMTBSApp/DMTBS/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result[] = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         DMTBSApp.DMTBSPackage.listHelper.write (out, $result);
         break;
       }

       case 5:  // DMTBSApp/DMTBS/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DMTBSApp/DMTBS/exchangeTickets
       {
         String customerID = in.read_string ();
         String oldMovieID = in.read_string ();
         String newMovieID = in.read_string ();
         String newMovieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, oldMovieID, newMovieID, newMovieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DMTBSApp/DMTBS/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DMTBSApp/DMTBS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DMTBS _this() 
  {
    return DMTBSHelper.narrow(
    super._this_object());
  }

  public DMTBS _this(org.omg.CORBA.ORB orb) 
  {
    return DMTBSHelper.narrow(
    super._this_object(orb));
  }


} // class DMTBSPOA
