package Replica3.DMTBSApp;


/**
* DMTBSApp/DMTBS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBSApp.idl
* Monday, April 10, 2023 9:29:09 o'clock PM EDT
*/

public interface DMTBS extends DMTBSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DMTBS
