package Replica4.DMTBSsystem;


/**
* DMTBSsystem/DMTBS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Monday, 10 April, 2023 10:25:45 PM EDT
*/

public interface DMTBS extends DMTBSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DMTBS
