package Replica4.DMTBSsystem;

/**
* DMTBSsystem/DMTBSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Monday, 10 April, 2023 10:25:45 PM EDT
*/

public final class DMTBSHolder implements org.omg.CORBA.portable.Streamable
{
  public DMTBS value = null;

  public DMTBSHolder ()
  {
  }

  public DMTBSHolder (Replica4.DMTBSsystem.DMTBS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = (DMTBS) Replica1.DMTBSapp.DMTBSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Replica4.DMTBSsystem.DMTBSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Replica4.DMTBSsystem.DMTBSHelper.type ();
  }

}
