package Replica4.DMTBSsystem;


import org.omg.CORBA.ORB;

/**
* DMTBSsystem/DMTBSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Monday, 10 April, 2023 10:25:45 PM EDT
*/

public abstract class DMTBSPOA extends org.omg.PortableServer.Servant
 implements Replica4.DMTBSsystem.DMTBSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addMovieSlots", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("listMovieShowsAvailability", new java.lang.Integer (2));
    _methods.put ("bookMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //First Start orbd follow Command :-  orbd -ORBInitialPort 1050
       case 0:  // DMTBSsystem/DMTBS/addMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addMovieSlots (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DMTBSsystem/DMTBS/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         String $result = null;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DMTBSsystem/DMTBS/listMovieShowsAvailability
       {
         String movieName = in.read_string ();
         String $result = null;
         $result = this.listMovieShowsAvailability (movieName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // DMTBSsystem/DMTBS/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DMTBSsystem/DMTBS/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DMTBSsystem/DMTBS/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DMTBSsystem/DMTBS/exchangeTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String new_movieID = in.read_string ();
         String new_movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         String $result = null;
         $result = this.exchangeTickets (customerID, movieID, new_movieID, new_movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DMTBSsystem/DMTBS/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DMTBSsystem/DMTBS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Replica4.DMTBSsystem.DMTBS _this()
  {
    return DMTBSHelper.narrow(
    super._this_object());
  }

  public Replica4.DMTBSsystem.DMTBS _this(ORB orb)
  {
    return DMTBSHelper.narrow(
    super._this_object(orb));
  }


} // class DMTBSPOA
